required = [
	"github.com/getlantern/deepcopy",
	"github.com/ghodss/yaml",
	"github.com/sirupsen/logrus",

	"github.com/openshift/ci-operator/pkg/api",

	"k8s.io/test-infra/prow/apis/prowjobs/v1",
	"k8s.io/test-infra/prow/client/clientset/versioned",
	"k8s.io/test-infra/prow/client/clientset/versioned/typed/prowjobs/v1",
	"k8s.io/test-infra/prow/pod-utils/downwardapi",
	"k8s.io/test-infra/prow/kube",
	"k8s.io/test-infra/prow/config",
	"k8s.io/test-infra/prow/pjutil",
	"k8s.io/test-infra/prow/github",

	"k8s.io/client-go/tools/clientcmd",
	"k8s.io/client-go/kubernetes/typed/core/v1",
	"k8s.io/client-go/kubernetes/fake",
	"k8s.io/api/core/v1",
	"k8s.io/apimachinery/pkg/apis/meta/v1",

	"k8s.io/apimachinery/pkg/api/equality",
	"k8s.io/apimachinery/pkg/util/diff",
]

[[constraint]]
  branch = "master"
  name = "k8s.io/test-infra"

# Fix vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:246:4: cannot use expiresIn (type string) as type json.Number in field value
# Fix vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:247:4: cannot use expiresOn (type string) as type json.Number in field value
# Fix vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:248:4: cannot use expiresOn (type string) as type json.Number in field value
# Fix vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:265:23: cannot use token.token.ExpiresIn (type json.Number) as type string in assignment
# Fix vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:266:23: cannot use token.token.ExpiresOn (type json.Number) as type string in assignment
[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "bca49d5b51a50dc5bb17bbf6204c711c6dbded06"

[[constraint]]
  name = "github.com/openshift/api"
  version = "3.9.0"

[[constraint]]
  name = "github.com/openshift/client-go"
  version = "3.9.0"
